version: '3'

services:
  service1:
    build:
      context: ./service1
    ports:
      - "8199:8199"  
    networks:
      - internal_network  
    depends_on:
      - service2  

  service2:
    build:
      context: ./service2
    networks:
      - internal_network  
    expose:
      - "3333" 

networks:
  internal_network:
    driver: bridge
